import React, { useEffect, useMemo, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertCircle, Eye, Pencil, Plus, RefreshCw, Search, ShoppingCart, Trash2, XCircle } from 'lucide-react';
import { createHttpApiClient } from '@/api/httpApiClient';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import ConfirmDialog from '@/components/ui/confirm-dialog';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import PaginationControls from '@/components/ui/PaginationControls';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Textarea } from '@/components/ui/textarea';
import { toast } from 'sonner';
import { buildPedidoPayload, calculatePedidoTotals, canUsePedidoAction, nextPedidoStatus, PEDIDO_STATUS_LABELS } from './pedidoUiPolicy';

const emptyItem = () => ({ produto_id:'', unidade_id:'', descricao:'', unidade_sigla:'', quantidade:'1', preco_unitario:'0', desconto:'0', requer_producao:false });
const emptyForm = () => ({ cliente_empresa_id:'', cliente_local_id:'', obra_id:'', tabela_preco_id:'', condicao_pagamento_id:'', tipo_operacao:'ENTREGA', data_entrega_solicitada:'', observacoes:'', itens:[emptyItem()] });
const money = (value) => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value||0));
const date = (value) => value ? new Intl.DateTimeFormat('pt-BR').format(new Date(value)) : '-';
const message = (error) => error?.status===403?'Seu perfil não possui permissão para esta ação.':error?.status===404?'Pedido não encontrado neste contexto.':error?.status===409?'O estado atual não permite esta ação.':error?.body?.error?.message||'Não foi possível concluir a operação.';

export default function PedidoCanonicoPanel({ groupId, empresaId, actorId, actorEmail, hasPermission, filterInContext, windowMode=false }) {
  const queryClient=useQueryClient(); const [page,setPage]=useState(1); const [pageSize,setPageSize]=useState(20); const [selected,setSelected]=useState(null); const [form,setForm]=useState(emptyForm); const [editing,setEditing]=useState(null); const [formOpen,setFormOpen]=useState(false); const [detailOpen,setDetailOpen]=useState(false); const [history,setHistory]=useState([]); const [dirty,setDirty]=useState(false); const [busy,setBusy]=useState(false); const [pendingCancel,setPendingCancel]=useState(null);
  const [filters,setFilters]=useState({search:'',status:'TODOS',clienteEmpresaId:'TODOS',tipoOperacao:'TODOS'}); const [applied,setApplied]=useState(filters);
  const canView=canUsePedidoAction(hasPermission,'visualizar'); const canCreate=canUsePedidoAction(hasPermission,'criar'); const canEdit=(row)=>canUsePedidoAction(hasPermission,'editar',row?.status); const canCancel=(row)=>canUsePedidoAction(hasPermission,'cancelar',row?.status); const canTransition=canUsePedidoAction(hasPermission,'alterar-status'); const ready=Boolean(groupId&&empresaId&&actorId);
  const api=useMemo(()=>createHttpApiClient({getScope:()=>({groupId,empresaId,actorId,actorEmail})}).pedidos,[groupId,empresaId,actorId,actorEmail]);
  const list=useQuery({queryKey:['pedidos-http',groupId,empresaId,page,pageSize,applied],queryFn:({signal})=>api.list({limit:pageSize,offset:(page-1)*pageSize,search:applied.search||undefined,status:applied.status==='TODOS'?undefined:applied.status,clienteEmpresaId:applied.clienteEmpresaId==='TODOS'?undefined:applied.clienteEmpresaId,tipoOperacao:applied.tipoOperacao==='TODOS'?undefined:applied.tipoOperacao,signal}),enabled:ready&&canView,retry:1});
  const master=useQuery({queryKey:['pedido-masters',groupId,empresaId],queryFn:async()=>{const [clientesEmpresa,clientes,condicoes,produtos,unidades,locais,obras,tabelas]=await Promise.all([filterInContext('ClienteEmpresa',{ativo:true,habilitado_operacao:true},'codigo',500),filterInContext('Cliente',{ativo:true},'razao_social',500),filterInContext('CondicaoPagamento',{ativo:true},'nome',500),filterInContext('Produto',{ativo:true},'descricao',500),filterInContext('UnidadeMedida',{ativo:true},'sigla',500),filterInContext('ClienteLocal',{ativo:true},'nome',500),filterInContext('Obra',{ativo:true},'nome',500),filterInContext('TabelaPreco',{ativo:true},'nome',500)]);return{clientesEmpresa,clientes,condicoes,produtos,unidades,locais,obras,tabelas};},enabled:ready&&canView,staleTime:30000});
  const masters=master.data||{clientesEmpresa:[],clientes:[],condicoes:[],produtos:[],unidades:[],locais:[],obras:[],tabelas:[]}; const clients=useMemo(()=>new Map(masters.clientes.map(x=>[x.id,x])),[masters.clientes]); const clientLabel=(id)=>{const link=masters.clientesEmpresa.find(x=>x.id===id);const row=clients.get(link?.cliente_id);return row?.razao_social||row?.nome_fantasia||row?.nome||link?.codigo||id;};
  useEffect(()=>{setPage(1);setSelected(null);setFormOpen(false);setDetailOpen(false);setFilters({search:'',status:'TODOS',clienteEmpresaId:'TODOS',tipoOperacao:'TODOS'});setApplied({search:'',status:'TODOS',clienteEmpresaId:'TODOS',tipoOperacao:'TODOS'});},[groupId,empresaId]);
  useEffect(()=>{const warn=(e)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
  const change=(key,value)=>{setForm(current=>({...current,[key]:value}));setDirty(true);}; const changeItem=(index,key,value)=>{setForm(current=>({...current,itens:current.itens.map((row,i)=>i===index?{...row,[key]:value}:row)}));setDirty(true);};
  const selectProduct=(index,id)=>{const product=masters.produtos.find(x=>x.id===id);const unit=masters.unidades.find(x=>x.id===product?.unidade_medida_id);setForm(current=>({...current,itens:current.itens.map((row,i)=>i===index?{...row,produto_id:id,unidade_id:product?.unidade_medida_id||'',descricao:product?.descricao||product?.nome||'',unidade_sigla:unit?.sigla||''}:row)}));setDirty(true);};
  const close=()=>{if(dirty&&!window.confirm('Descartar as alterações deste pedido?'))return;setFormOpen(false);setDirty(false);setEditing(null);}; const openCreate=()=>{setEditing(null);setForm(emptyForm());setDirty(false);setFormOpen(true);};
  const openEdit=(row)=>{if(!canEdit(row))return;setEditing(row);setForm({cliente_empresa_id:row.cliente_empresa_id,cliente_local_id:row.cliente_local_id||'',obra_id:row.obra_id||'',tabela_preco_id:row.tabela_preco_id||'',condicao_pagamento_id:row.condicao_pagamento_id,tipo_operacao:row.tipo_operacao,data_entrega_solicitada:String(row.data_entrega_solicitada||'').slice(0,10),observacoes:row.observacoes||'',itens:row.itens.map(item=>({produto_id:item.produto_id,unidade_id:item.unidade_id,descricao:item.descricao,unidade_sigla:item.unidade_sigla,quantidade:item.quantidade,preco_unitario:item.preco_unitario,desconto:item.desconto,requer_producao:item.requer_producao}))});setDirty(false);setDetailOpen(false);setFormOpen(true);};
  const save=async()=>{if(busy)return;setBusy(true);try{const payload=buildPedidoPayload(form);const saved=editing?await api.update(editing.id,payload):await api.create(payload);toast.success(editing?'Pedido atualizado.':'Pedido criado.');setSelected(saved);setDirty(false);setFormOpen(false);setEditing(null);await queryClient.invalidateQueries({queryKey:['pedidos-http',groupId,empresaId]});}catch(error){toast.error(message(error));}finally{setBusy(false);}};
  const show=async(row)=>{try{const [detail,events]=await Promise.all([api.get(row.id),api.history(row.id)]);setSelected(detail);setHistory(events);setDetailOpen(true);}catch(error){toast.error(message(error));}};
  const transition=async(row)=>{const target=nextPedidoStatus(row);if(!target||busy)return;setBusy(true);try{const updated=await api.transition(row.id,target);setSelected(updated);setHistory(await api.history(row.id));toast.success(`Pedido movido para ${PEDIDO_STATUS_LABELS[target]}.`);await queryClient.invalidateQueries({queryKey:['pedidos-http',groupId,empresaId]});}catch(error){toast.error(message(error));}finally{setBusy(false);}};
  const cancel=async(row)=>{if(!row||busy)return;setBusy(true);try{const updated=await api.cancel(row.id,'Cancelamento confirmado pelo usuário');setSelected(updated);setHistory(await api.history(row.id));toast.success('Pedido cancelado e preservado.');await queryClient.invalidateQueries({queryKey:['pedidos-http',groupId,empresaId]});}catch(error){toast.error(message(error));}finally{setBusy(false);}};
  if(!canView)return <div className="w-full h-full flex items-center justify-center p-6"><Alert className="max-w-lg"><AlertCircle className="h-4 w-4"/><AlertDescription>Acesso negado aos Pedidos.</AlertDescription></Alert></div>;
  const rows=list.data?.data||[];const meta=list.data?.meta||{total:0};let totals={subtotal:'0',desconto:'0',total:'0'};try{totals=calculatePedidoTotals(form.itens);}catch{totals={subtotal:'0',desconto:'0',total:'0'};}
  return <div className={`w-full h-full flex flex-col bg-slate-50 ${windowMode?'p-3':'p-4'}`} data-permission="Comercial.pedido.visualizar">
    <div className="flex flex-wrap items-center justify-between gap-3 mb-3"><div><h2 className="text-xl font-semibold">Pedidos</h2><p className="text-sm text-slate-500">Operação comercial da empresa ativa</p></div>{canCreate&&<Button onClick={openCreate} disabled={!ready}><Plus className="w-4 h-4 mr-2"/>Novo pedido</Button>}</div>
    {!ready&&<Alert><AlertCircle className="h-4 w-4"/><AlertDescription>Selecione uma empresa e entre com um usuário válido.</AlertDescription></Alert>}
    <form className="grid grid-cols-1 md:grid-cols-6 gap-2 mb-3" onSubmit={e=>{e.preventDefault();setPage(1);setApplied(filters);}}><div className="md:col-span-2"><Input aria-label="Pesquisar pedido" maxLength={80} placeholder="Número do pedido" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/></div><Select value={filters.status} onValueChange={v=>setFilters({...filters,status:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="TODOS">Todos os status</SelectItem>{Object.entries(PEDIDO_STATUS_LABELS).map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select><Select value={filters.tipoOperacao} onValueChange={v=>setFilters({...filters,tipoOperacao:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="TODOS">Entrega e retirada</SelectItem><SelectItem value="ENTREGA">Entrega</SelectItem><SelectItem value="RETIRADA">Retirada</SelectItem></SelectContent></Select><Select value={filters.clienteEmpresaId} onValueChange={v=>setFilters({...filters,clienteEmpresaId:v})}><SelectTrigger><SelectValue placeholder="Clientes"/></SelectTrigger><SelectContent><SelectItem value="TODOS">Todos os clientes</SelectItem>{masters.clientesEmpresa.map(x=><SelectItem key={x.id} value={x.id}>{clientLabel(x.id)}</SelectItem>)}</SelectContent></Select><div className="flex gap-2"><Button type="submit" variant="outline" className="flex-1"><Search className="w-4 h-4 mr-2"/>Filtrar</Button><Button type="button" size="icon" variant="ghost" title="Limpar filtros" onClick={()=>{const clean={search:'',status:'TODOS',clienteEmpresaId:'TODOS',tipoOperacao:'TODOS'};setFilters(clean);setApplied(clean);setPage(1);}}><RefreshCw className="w-4 h-4"/></Button></div></form>
    {list.isLoading?<div className="flex-1 flex items-center justify-center">Carregando pedidos...</div>:list.isError?<div className="flex-1 flex flex-col items-center justify-center gap-3"><p>{message(list.error)}</p><Button variant="outline" onClick={()=>list.refetch()}>Tentar novamente</Button></div>:rows.length===0?<div className="flex-1 flex flex-col items-center justify-center text-slate-500"><ShoppingCart className="w-10 h-10 mb-2"/><p>Nenhum pedido encontrado nesta empresa.</p></div>:<div className="flex-1 min-h-0 overflow-auto border bg-white rounded-md"><Table><TableHeader><TableRow><TableHead>Número</TableHead><TableHead>Cliente</TableHead><TableHead>Operação</TableHead><TableHead>Entrega solicitada</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Total</TableHead><TableHead className="text-right">Ações</TableHead></TableRow></TableHeader><TableBody>{rows.map(row=><TableRow key={row.id}><TableCell className="font-mono">{row.numero}</TableCell><TableCell>{clientLabel(row.cliente_empresa_id)}</TableCell><TableCell>{row.tipo_operacao==='ENTREGA'?'Entrega':'Retirada'}</TableCell><TableCell>{date(row.data_entrega_solicitada)}</TableCell><TableCell><Badge variant={row.status==='CANCELADO'?'secondary':'default'}>{PEDIDO_STATUS_LABELS[row.status]||row.status}</Badge></TableCell><TableCell className="text-right font-semibold">{money(row.total)}</TableCell><TableCell><div className="flex justify-end gap-1"><Button size="icon" variant="ghost" title="Visualizar" onClick={()=>show(row)}><Eye className="w-4 h-4"/></Button>{canEdit(row)&&<Button size="icon" variant="ghost" title="Editar" onClick={()=>openEdit(row)}><Pencil className="w-4 h-4"/></Button>}{canCancel(row)&&<Button size="icon" variant="ghost" title="Cancelar" onClick={()=>setPendingCancel(row)}><XCircle className="w-4 h-4"/></Button>}</div></TableCell></TableRow>)}</TableBody></Table></div>}
    <PaginationControls currentPage={page} totalItems={meta.total||0} itemsPerPage={pageSize} onPageChange={setPage} onItemsPerPageChange={setPageSize} isLoading={list.isFetching}/>
    <Dialog open={formOpen} onOpenChange={open=>{if(!open)close();}}><DialogContent className="w-[96vw] max-w-6xl max-h-[92vh] overflow-auto"><DialogHeader><DialogTitle>{editing?`Editar pedido ${editing.numero}`:'Novo pedido'}</DialogTitle><DialogDescription>Valores e referências serão validados novamente pelo servidor.</DialogDescription></DialogHeader><div className="grid grid-cols-1 md:grid-cols-4 gap-3"><div className="md:col-span-2"><Label>Cliente</Label><Select value={form.cliente_empresa_id} onValueChange={v=>change('cliente_empresa_id',v)}><SelectTrigger><SelectValue placeholder="Selecione"/></SelectTrigger><SelectContent>{masters.clientesEmpresa.filter(x=>x.ativo!==false&&x.habilitado_operacao!==false&&!x.bloqueado).map(x=><SelectItem key={x.id} value={x.id}>{clientLabel(x.id)}</SelectItem>)}</SelectContent></Select></div><div><Label>Condição</Label><Select value={form.condicao_pagamento_id} onValueChange={v=>change('condicao_pagamento_id',v)}><SelectTrigger><SelectValue placeholder="Selecione"/></SelectTrigger><SelectContent>{masters.condicoes.map(x=><SelectItem key={x.id} value={x.id}>{x.nome||x.codigo}</SelectItem>)}</SelectContent></Select></div><div><Label>Operação</Label><Select value={form.tipo_operacao} onValueChange={v=>change('tipo_operacao',v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="ENTREGA">Entrega</SelectItem><SelectItem value="RETIRADA">Retirada</SelectItem></SelectContent></Select></div><div><Label>Data solicitada</Label><Input type="date" value={form.data_entrega_solicitada} onChange={e=>change('data_entrega_solicitada',e.target.value)}/></div><div><Label>Local</Label><Select value={form.cliente_local_id||'NENHUM'} onValueChange={v=>change('cliente_local_id',v==='NENHUM'?'':v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="NENHUM">Não informado</SelectItem>{masters.locais.map(x=><SelectItem key={x.id} value={x.id}>{x.nome||x.apelido||x.id}</SelectItem>)}</SelectContent></Select></div><div><Label>Obra</Label><Select value={form.obra_id||'NENHUMA'} onValueChange={v=>change('obra_id',v==='NENHUMA'?'':v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="NENHUMA">Sem obra</SelectItem>{masters.obras.map(x=><SelectItem key={x.id} value={x.id}>{x.nome||x.codigo}</SelectItem>)}</SelectContent></Select></div><div><Label>Tabela de preço</Label><Select value={form.tabela_preco_id||'NENHUMA'} onValueChange={v=>change('tabela_preco_id',v==='NENHUMA'?'':v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="NENHUMA">Não informada</SelectItem>{masters.tabelas.map(x=><SelectItem key={x.id} value={x.id}>{x.nome||x.codigo}</SelectItem>)}</SelectContent></Select></div><div className="md:col-span-4"><Label>Observações</Label><Textarea value={form.observacoes} onChange={e=>change('observacoes',e.target.value)}/></div></div>
    <div className="space-y-2"><div className="flex justify-between"><h3 className="font-semibold">Itens</h3><Button type="button" variant="outline" size="sm" onClick={()=>change('itens',[...form.itens,emptyItem()])}><Plus className="w-4 h-4 mr-1"/>Item</Button></div>{form.itens.map((item,index)=><div key={index} className="grid grid-cols-1 md:grid-cols-12 gap-2 border rounded-md p-2"><div className="md:col-span-3"><Label>Produto</Label><Select value={item.produto_id} onValueChange={v=>selectProduct(index,v)}><SelectTrigger><SelectValue placeholder="Selecione"/></SelectTrigger><SelectContent>{masters.produtos.map(p=><SelectItem key={p.id} value={p.id}>{p.codigo?`${p.codigo} - `:''}{p.descricao||p.nome}</SelectItem>)}</SelectContent></Select></div><div className="md:col-span-3"><Label>Descrição</Label><Input value={item.descricao} onChange={e=>changeItem(index,'descricao',e.target.value)}/></div><div><Label>Un.</Label><Input value={item.unidade_sigla} readOnly/></div><div><Label>Qtd.</Label><Input value={item.quantidade} onChange={e=>changeItem(index,'quantidade',e.target.value)}/></div><div><Label>Preço</Label><Input value={item.preco_unitario} onChange={e=>changeItem(index,'preco_unitario',e.target.value)}/></div><div><Label>Desconto</Label><Input value={item.desconto} onChange={e=>changeItem(index,'desconto',e.target.value)}/></div><div className="flex items-end gap-2"><Checkbox checked={item.requer_producao} onCheckedChange={v=>changeItem(index,'requer_producao',Boolean(v))}/><span className="text-xs">Produção</span></div><div className="flex items-end"><Button type="button" size="icon" variant="ghost" disabled={form.itens.length===1} onClick={()=>change('itens',form.itens.filter((_,i)=>i!==index))}><Trash2 className="w-4 h-4"/></Button></div></div>)}</div><div className="flex justify-end gap-5 text-sm"><span>Subtotal: <strong>{money(totals.subtotal)}</strong></span><span>Desconto: <strong>{money(totals.desconto)}</strong></span><span>Total: <strong>{money(totals.total)}</strong></span></div><DialogFooter><Button variant="outline" onClick={close}>Fechar</Button><Button onClick={save} disabled={busy||master.isLoading}>{busy?'Salvando...':'Salvar pedido'}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={detailOpen} onOpenChange={setDetailOpen}><DialogContent className="max-w-5xl max-h-[92vh] overflow-auto"><DialogHeader><DialogTitle>Pedido {selected?.numero}</DialogTitle><DialogDescription>{PEDIDO_STATUS_LABELS[selected?.status]||selected?.status} · {selected?.tipo_operacao==='ENTREGA'?'Entrega':'Retirada'} em {date(selected?.data_entrega_solicitada)}</DialogDescription></DialogHeader>{selected&&<div className="space-y-4"><Table><TableHeader><TableRow><TableHead>Item</TableHead><TableHead>Un.</TableHead><TableHead>Qtd.</TableHead><TableHead>Produção</TableHead><TableHead className="text-right">Total</TableHead></TableRow></TableHeader><TableBody>{selected.itens.map(item=><TableRow key={item.id}><TableCell>{item.descricao}</TableCell><TableCell>{item.unidade_sigla}</TableCell><TableCell>{item.quantidade}</TableCell><TableCell>{item.requer_producao?'Sim':'Não'}</TableCell><TableCell className="text-right">{money(item.total)}</TableCell></TableRow>)}</TableBody></Table><div className="flex justify-end gap-4"><strong>Total: {money(selected.total)}</strong></div><div><h3 className="font-semibold mb-2">Histórico</h3><div className="space-y-1">{history.map(event=><div key={event.id} className="text-sm border-l-2 pl-3"><strong>{PEDIDO_STATUS_LABELS[event.status_novo]}</strong> · {date(event.created_at)}{event.motivo?` · ${event.motivo}`:''}</div>)}</div></div></div>}<DialogFooter className="flex flex-wrap gap-2">{canEdit(selected)&&<Button variant="outline" onClick={()=>openEdit(selected)}><Pencil className="w-4 h-4 mr-2"/>Editar</Button>}{canTransition&&nextPedidoStatus(selected)&&<Button onClick={()=>transition(selected)} disabled={busy}>Avançar para {PEDIDO_STATUS_LABELS[nextPedidoStatus(selected)]}</Button>}{canCancel(selected)&&<Button variant="destructive" onClick={()=>setPendingCancel(selected)} disabled={busy}>Cancelar pedido</Button>}</DialogFooter></DialogContent></Dialog>
    <ConfirmDialog open={Boolean(pendingCancel)} onOpenChange={open=>{if(!open)setPendingCancel(null);}} onConfirm={()=>{const row=pendingCancel;setPendingCancel(null);void cancel(row);}} title="Cancelar pedido?" description="O pedido, seus itens e o histórico serão preservados." confirmText="Cancelar pedido" variant="warning"/>
  </div>;
}
