import {
  Eye,
  Pencil,
  Trash2,
  Plus,
  CheckSquare,
  Download,
  LayoutDashboard,
  ShoppingCart,
  DollarSign,
  Package,
  Truck,
  Factory,
  UserCircle,
  FileText,
  BarChart3,
  Users,
  MessageCircle,
  Briefcase,
  Calendar,
  Settings,
} from "lucide-react";

export const ESTRUTURA_SISTEMA = {
  dashboard: { nome: "Dashboard", icone: LayoutDashboard, cor: "blue", secoes: { principal: { nome: "Visao Geral", abas: ["kpis", "graficos", "alertas"] }, corporativo: { nome: "Dashboard Corporativo", abas: ["multiempresa", "consolidado"] } } },
  comercial: { nome: "Comercial e Vendas", icone: ShoppingCart, cor: "green", secoes: { clientes: { nome: "Clientes", abas: ["lista", "detalhes", "historico", "crm"] }, pedidos: { nome: "Pedidos", abas: ["lista", "novo", "aprovacao", "faturamento"] }, orcamentos: { nome: "Orcamentos", abas: ["lista", "novo", "conversao"] }, tabelas_preco: { nome: "Tabelas de Preco", abas: ["lista", "itens"] }, comissoes: { nome: "Comissoes", abas: ["lista", "calculo", "pagamento"] }, notas_fiscais: { nome: "Notas Fiscais", abas: ["emissao", "lista", "cancelamento"] } } },
  financeiro: { nome: "Financeiro e Contabil", icone: DollarSign, cor: "emerald", secoes: { contas_receber: { nome: "Contas a Receber", abas: ["lista", "baixa", "cobranca", "boletos"] }, contas_pagar: { nome: "Contas a Pagar", abas: ["lista", "baixa", "aprovacao", "pagamento"] }, caixa: { nome: "Caixa Diario", abas: ["movimentos", "fechamento", "transferencias"] }, conciliacao: { nome: "Conciliacao Bancaria", abas: ["importar", "conciliar", "historico"] }, relatorios: { nome: "Relatorios Financeiros", abas: ["dre", "fluxo_caixa", "inadimplencia"] } } },
  estoque: { nome: "Estoque e Almoxarifado", icone: Package, cor: "purple", secoes: { produtos: { nome: "Produtos", abas: ["lista", "novo", "lotes", "validade"] }, movimentacoes: { nome: "Movimentacoes", abas: ["entrada", "saida", "transferencia", "ajuste"] }, inventario: { nome: "Inventario", abas: ["contagem", "acerto", "historico"] }, requisicoes: { nome: "Requisicoes", abas: ["lista", "aprovacao", "atendimento"] } } },
  compras: { nome: "Compras e Suprimentos", icone: Briefcase, cor: "orange", secoes: { fornecedores: { nome: "Fornecedores", abas: ["lista", "avaliacao", "historico"] }, solicitacoes: { nome: "Solicitacoes", abas: ["lista", "nova", "aprovacao"] }, cotacoes: { nome: "Cotacoes", abas: ["lista", "nova", "comparativo"] }, ordens_compra: { nome: "Ordens de Compra", abas: ["lista", "nova", "recebimento"] } } },
  expedicao: { nome: "Expedicao e Logistica", icone: Truck, cor: "cyan", secoes: { entregas: { nome: "Entregas", abas: ["lista", "separacao", "despacho", "rastreamento"] }, romaneios: { nome: "Romaneios", abas: ["lista", "novo", "impressao"] }, roteirizacao: { nome: "Roteirizacao", abas: ["mapa", "otimizacao", "motoristas"] }, transportadoras: { nome: "Transportadoras", abas: ["lista", "tabelas_frete"] } } },
  producao: { nome: "Producao e Manufatura", icone: Factory, cor: "indigo", secoes: { ordens_producao: { nome: "Ordens de Producao", abas: ["lista", "nova", "programacao", "kanban"] }, apontamentos: { nome: "Apontamentos", abas: ["producao", "paradas", "refugo"] }, qualidade: { nome: "Qualidade", abas: ["inspecao", "nao_conformidades", "acoes"] } } },
  rh: { nome: "Recursos Humanos", icone: UserCircle, cor: "pink", secoes: { colaboradores: { nome: "Colaboradores", abas: ["lista", "documentos", "historico"] }, ponto: { nome: "Ponto Eletronico", abas: ["registros", "ajustes", "relatorios"] }, ferias: { nome: "Ferias", abas: ["programacao", "solicitacoes", "aprovacao"] }, folha: { nome: "Folha de Pagamento", abas: ["calculo", "holerites", "encargos"] } } },
  fiscal: { nome: "Fiscal e Tributario", icone: FileText, cor: "red", secoes: { nfe: { nome: "NF-e", abas: ["emissao", "entrada", "manifestacao", "inutilizacao"] }, tabelas_fiscais: { nome: "Tabelas Fiscais", abas: ["cfop", "cst", "ncm", "aliquotas"] }, sped: { nome: "SPED", abas: ["fiscal", "contribuicoes", "contabil"] }, obrigacoes: { nome: "Obrigacoes Acessorias", abas: ["calendario", "guias", "declaracoes"] } } },
  cadastros: { nome: "Cadastros Gerais", icone: Users, cor: "slate", secoes: { pessoas: { nome: "Pessoas & Parceiros", abas: ["clientes", "fornecedores", "transportadoras", "colaboradores"] }, produtos: { nome: "Produtos & Servicos", abas: ["produtos", "servicos", "grupos", "marcas"] }, financeiro: { nome: "Financeiro", abas: ["bancos", "formas_pagamento", "centros_custo"] }, logistica: { nome: "Logistica", abas: ["veiculos", "motoristas", "rotas"] }, organizacional: { nome: "Organizacional", abas: ["empresas", "departamentos", "cargos", "usuarios"] }, integracoes: { nome: "Integracoes & IA", abas: ["apis", "webhooks", "chatbot", "jobs_ia"] } } },
  crm: { nome: "CRM - Relacionamento", icone: MessageCircle, cor: "violet", secoes: { oportunidades: { nome: "Oportunidades", abas: ["funil", "lista", "conversao"] }, interacoes: { nome: "Interacoes", abas: ["historico", "nova", "follow_up"] }, campanhas: { nome: "Campanhas", abas: ["lista", "nova", "resultados"] } } },
  agenda: { nome: "Agenda e Calendario", icone: Calendar, cor: "amber", secoes: { eventos: { nome: "Eventos", abas: ["calendario", "lista", "notificacoes"] }, tarefas: { nome: "Tarefas", abas: ["kanban", "lista", "atribuicao"] } } },
  relatorios: { nome: "Relatorios e Analises", icone: BarChart3, cor: "teal", secoes: { dashboards: { nome: "Dashboards", abas: ["executivo", "operacional", "financeiro"] }, relatorios: { nome: "Relatorios", abas: ["vendas", "estoque", "financeiro", "rh"] }, exportacao: { nome: "Exportacao", abas: ["excel", "pdf", "api"] } } },
  sistema: { nome: "Configuracoes do Sistema", icone: Settings, cor: "gray", secoes: { configuracoes: { nome: "Configuracoes Gerais", abas: ["geral", "notificacoes", "backup"] }, integracoes: { nome: "Integracoes", abas: ["nfe", "boletos", "whatsapp", "marketplaces"] }, acessos: { nome: "Controle de Acesso", abas: ["perfis", "usuarios", "grupos"] }, ia: { nome: "IA & Otimizacao", abas: ["modelos", "limites", "logs"] } } },
};

export const ACOES = [
  { id: "visualizar", nome: "Visualizar", icone: Eye, cor: "slate" },
  { id: "criar", nome: "Criar", icone: Plus, cor: "blue" },
  { id: "editar", nome: "Editar", icone: Pencil, cor: "green" },
  { id: "excluir", nome: "Excluir", icone: Trash2, cor: "red" },
  { id: "aprovar", nome: "Aprovar", icone: CheckSquare, cor: "purple" },
  { id: "exportar", nome: "Exportar", icone: Download, cor: "cyan" },
];

export const COR_CLASS = {
  blue: "text-blue-600",
  green: "text-green-600",
  emerald: "text-emerald-600",
  purple: "text-purple-600",
  orange: "text-orange-600",
  cyan: "text-cyan-600",
  indigo: "text-indigo-600",
  pink: "text-pink-600",
  slate: "text-slate-600",
  red: "text-red-600",
  violet: "text-violet-600",
  amber: "text-amber-600",
  teal: "text-teal-600",
  sky: "text-sky-600",
  gray: "text-gray-600",
};
