export {
  CRM_ENTITIES,
  CRM_ETAPAS,
  isCrmEntity,
  digitsOnly,
  normalizeEtapaCrm,
  oportunidadeAberta,
  oportunidadeIdempotencyKey,
  findDuplicateOportunidade,
  stampOportunidadeDefaults,
  assertOportunidadeOnCreate,
  assertInteracaoOnCreate,
  assertCampanhaOnCreate,
  assertOportunidadeOnUpdate,
  oportunidadeStatusPermissionActions,
  assertConversaoOportunidade,
  buildDocumentoFromOportunidade,
  stampOportunidadeConvertida,
  applyCrmCreate,
} from './crmOportunidadePolicy.js';
