import { randomUUID } from 'node:crypto';
import type { DbQueryExecutor } from '../db/client.js';
import { calculateOrcamento, type Orcamento, type OrcamentoCreate, type OrcamentoRepository, type OrcamentoScope } from './orcamentoTypes.js';
export class InMemoryOrcamentoRepository implements OrcamentoRepository { private rows=new Map<string,Orcamento>(); private next=new Map<string,number>();
 async withTransaction<T>(fn:(executor?:DbQueryExecutor)=>Promise<T>){const rows=structuredClone(this.rows),next=new Map(this.next);try{return await fn();}catch(e){this.rows=rows;this.next=next;throw e;}}
 async create(s:OrcamentoScope,d:OrcamentoCreate,_executor?:DbQueryExecutor){const now=new Date().toISOString(),id=randomUUID(),n=this.next.get(s.empresaId)??1,t=calculateOrcamento(d.itens),r:Orcamento={id,group_id:s.groupId,empresa_id:s.empresaId,numero:String(n).padStart(8,'0'),status:'EM_ABERTO',cliente_empresa_id:d.cliente_empresa_id,condicao_pagamento_id:d.condicao_pagamento_id,validade_em:d.validade_em,observacoes:d.observacoes??null,desconto:t.desconto,subtotal:t.subtotal,total:t.total,ativo:true,itens:t.itens,created_at:now,updated_at:now};this.next.set(s.empresaId,n+1);this.rows.set(id,r);return structuredClone(r)}
 async get(s:OrcamentoScope,id:string,_executor?:DbQueryExecutor){const r=this.rows.get(id);return r&&r.group_id===s.groupId&&r.empresa_id===s.empresaId?structuredClone(r):null}
 async list(s:OrcamentoScope,l=50,o=0,_executor?:DbQueryExecutor){const r=[...this.rows.values()].filter(x=>x.group_id===s.groupId&&x.empresa_id===s.empresaId).sort((a,b)=>b.numero.localeCompare(a.numero)||b.id.localeCompare(a.id));return{rows:structuredClone(r.slice(o,o+l)),total:r.length}}
 async update(s:OrcamentoScope,id:string,d:OrcamentoCreate,_executor?:DbQueryExecutor){const r=await this.get(s,id);if(!r||r.status!=='EM_ABERTO')return null;const t=calculateOrcamento(d.itens),n={...r,...d,observacoes:d.observacoes??null,itens:t.itens,subtotal:t.subtotal,desconto:t.desconto,total:t.total,updated_at:new Date().toISOString()};this.rows.set(id,n);return structuredClone(n)}
 async cancel(s:OrcamentoScope,id:string,_executor?:DbQueryExecutor){const r=await this.get(s,id);if(!r||r.status!=='EM_ABERTO')return null;const n={...r,status:'CANCELADO' as const,ativo:false,updated_at:new Date().toISOString()};this.rows.set(id,n);return structuredClone(n)} }