import type { DbQueryExecutor } from '../db/client.js';
import { z } from 'zod';
const money=z.string().regex(/^\d+(\.\d{1,6})?$/).transform(v=>v.includes('.')?`${v.split('.')[0]}.${(v.split('.')[1]+'000000').slice(0,6)}`:`${v}.000000`);
export const orcamentoItemSchema=z.object({produto_id:z.string().uuid(),unidade_id:z.string().uuid(),descricao:z.string().trim().min(1).max(240),unidade_sigla:z.string().trim().min(1).max(12),quantidade:money,preco_unitario:money,desconto:money.optional()}).strict();
export const orcamentoCreateSchema=z.object({cliente_empresa_id:z.string().uuid(),condicao_pagamento_id:z.string().uuid(),validade_em:z.string().datetime(),observacoes:z.string().trim().max(1000).optional(),itens:z.array(orcamentoItemSchema).min(1).max(1000)}).strict();
export type OrcamentoCreate=z.infer<typeof orcamentoCreateSchema>; export type OrcamentoItem=z.infer<typeof orcamentoItemSchema> & {subtotal:string;total:string}; export type Orcamento={id:string;group_id:string;empresa_id:string;numero:string;status:'EM_ABERTO'|'CANCELADO';cliente_empresa_id:string;condicao_pagamento_id:string;validade_em:string;observacoes:string|null;subtotal:string;desconto:string;total:string;ativo:boolean;itens:OrcamentoItem[];created_at:string;updated_at:string};
const micros=(v:string)=>{const [i,f='']=v.split('.');return BigInt(i)*1000000n+BigInt((f+'000000').slice(0,6));}; const fmt=(v:bigint)=>`${v/1000000n}.${(v%1000000n).toString().padStart(6,'0')}`;
export function calculateOrcamento(items: z.infer<typeof orcamentoItemSchema>[]):Pick<Orcamento,'itens'|'subtotal'|'desconto'|'total'>{let subtotal=0n,desconto=0n;const rows=items.map(i=>{const s=micros(i.quantidade)*micros(i.preco_unitario)/1000000n,d=micros(i.desconto??'0');if(d>s)throw new Error('ORCAMENTO_DESCONTO_INVALIDO');subtotal+=s;desconto+=d;return {...i,subtotal:fmt(s),total:fmt(s-d)};});return{itens:rows,subtotal:fmt(subtotal),desconto:fmt(desconto),total:fmt(subtotal-desconto)}}

export type OrcamentoScope={groupId:string;empresaId:string}; export type OrcamentoPage={rows:Orcamento[];total:number}; export type OrcamentoListFilters={search?:string;status?:Orcamento['status'];clienteEmpresaId?:string;validadeDe?:string;validadeAte?:string}; export type OrcamentoRepository={withTransaction<T>(fn:(executor?:DbQueryExecutor)=>Promise<T>):Promise<T>;create(scope:OrcamentoScope,data:OrcamentoCreate,executor?:DbQueryExecutor):Promise<Orcamento>;get(scope:OrcamentoScope,id:string,executor?:DbQueryExecutor):Promise<Orcamento|null>;list(scope:OrcamentoScope,limit?:number,offset?:number,executor?:DbQueryExecutor,filters?:OrcamentoListFilters):Promise<OrcamentoPage>;update(scope:OrcamentoScope,id:string,data:OrcamentoCreate,executor?:DbQueryExecutor):Promise<Orcamento|null>;cancel(scope:OrcamentoScope,id:string,executor?:DbQueryExecutor):Promise<Orcamento|null>};
