import type { DbClient, DbQueryExecutor } from '../db/client.js';
import type { CondicaoPagamentoRepository, CondicaoPagamentoListFilter, CondicaoPagamentoScope } from './inMemoryCondicaoPagamentoRepository.js';
import type { CondicaoPagamento, CondicaoPagamentoCreate, CondicaoPagamentoEmpresa, CondicaoPagamentoParcela, CondicaoPagamentoParcelaInput, CondicaoPagamentoUpdate } from './condicaoPagamentoTypes.js';
const iso=(v:unknown)=>v instanceof Date?v.toISOString():String(v??'');
export class PostgresCondicaoPagamentoRepository implements CondicaoPagamentoRepository {
  constructor(private readonly db:DbClient){} private q(tx?:DbQueryExecutor){return tx??this.db;}
  withTransaction<T>(fn:(tx?:DbQueryExecutor)=>Promise<T>){return this.db.withTransaction(fn);}
  private async row(id:string,groupId:string,empresaId?:string|null,tx?:DbQueryExecutor):Promise<CondicaoPagamento|null>{const q=this.q(tx);const r=await q.query<any>(`SELECT c.* FROM condicoes_pagamento c WHERE c.id=$1 AND c.group_id=$2 ${empresaId?`AND EXISTS(SELECT 1 FROM condicao_pagamento_empresas e WHERE e.condicao_pagamento_id=c.id AND e.group_id=c.group_id AND e.empresa_id=$3 AND e.ativo)`:''}`,[id,groupId,...(empresaId?[empresaId]:[])]);if(!r.rows[0])return null;const c=r.rows[0], [e,p]=await Promise.all([q.query<any>('SELECT * FROM condicao_pagamento_empresas WHERE condicao_pagamento_id=$1 AND group_id=$2 ORDER BY created_at',[id,groupId]),q.query<any>('SELECT * FROM condicao_pagamento_parcelas WHERE condicao_pagamento_id=$1 AND group_id=$2 ORDER BY ordem',[id,groupId])]);return {...c,id:String(c.id),group_id:String(c.group_id),empresa_id:String(c.empresa_id),codigo:String(c.codigo),nome:String(c.nome),descricao:c.descricao??null,ativo:Boolean(c.ativo),codigo_condicao_legado:c.codigo_condicao_legado??null,origem:String(c.origem),legacy_id:c.legacy_id??null,legacy_code:c.legacy_code??null,source_system:c.source_system??null,migration_batch:c.migration_batch??null,imported_at:c.imported_at?iso(c.imported_at):null,created_by:c.created_by?String(c.created_by):null,updated_by:c.updated_by?String(c.updated_by):null,created_at:iso(c.created_at),updated_at:iso(c.updated_at),empresas:e.rows.map((x:any)=>({...x,id:String(x.id),group_id:String(x.group_id),condicao_pagamento_id:String(x.condicao_pagamento_id),empresa_id:String(x.empresa_id),eh_padrao:Boolean(x.eh_padrao),ativo:Boolean(x.ativo),created_by:x.created_by?String(x.created_by):null,updated_by:x.updated_by?String(x.updated_by):null,created_at:iso(x.created_at),updated_at:iso(x.updated_at)}) as CondicaoPagamentoEmpresa),parcelas:p.rows.map((x:any)=>({...x,id:String(x.id),group_id:String(x.group_id),condicao_pagamento_id:String(x.condicao_pagamento_id),ordem:Number(x.ordem),dias:Number(x.dias),percentual:String(x.percentual),ativo:Boolean(x.ativo),created_by:x.created_by?String(x.created_by):null,updated_by:x.updated_by?String(x.updated_by):null,created_at:iso(x.created_at),updated_at:iso(x.updated_at)}) as CondicaoPagamentoParcela)};}
  async listPage(f:CondicaoPagamentoListFilter,tx?:DbQueryExecutor){const q=this.q(tx);const p:any[]=[f.groupId,f.empresaId];let w='c.group_id=$1 AND EXISTS(SELECT 1 FROM condicao_pagamento_empresas e WHERE e.condicao_pagamento_id=c.id AND e.group_id=c.group_id AND e.empresa_id=$2 AND e.ativo)';if(f.ativo!==undefined){p.push(f.ativo);w+=` AND c.ativo=$${p.length}`;}if(f.ehPadrao){w+=' AND EXISTS(SELECT 1 FROM condicao_pagamento_empresas ep WHERE ep.condicao_pagamento_id=c.id AND ep.empresa_id=$2 AND ep.ativo AND ep.eh_padrao)';}if(f.search){p.push(`%${f.search}%`);w+=` AND (c.nome ILIKE $${p.length} OR c.codigo ILIKE $${p.length})`;}const count=await q.query<any>(`SELECT count(*)::int total FROM condicoes_pagamento c WHERE ${w}`,p);p.push(f.limit,f.offset);const ids=await q.query<any>(`SELECT c.id FROM condicoes_pagamento c WHERE ${w} ORDER BY c.nome LIMIT $${p.length-1} OFFSET $${p.length}`,p);return {rows:(await Promise.all(ids.rows.map((x:any)=>this.row(String(x.id),f.groupId,f.empresaId,tx)))).filter(Boolean) as CondicaoPagamento[],total:Number(count.rows[0].total)};}
  get(s:CondicaoPagamentoScope,id:string,tx?:DbQueryExecutor){return this.row(id,s.groupId,s.empresaId,tx);}
  async create(s:{groupId:string;empresaId:string},d:CondicaoPagamentoCreate,a:string|null|undefined,tx?:DbQueryExecutor){const q=this.q(tx);const r=await q.query<any>(`INSERT INTO condicoes_pagamento(group_id,empresa_id,codigo,nome,descricao,codigo_condicao_legado,origem,legacy_id,legacy_code,source_system,migration_batch,imported_at,created_by,updated_by) VALUES($1,$2,reserve_entity_codigo($1,'CondicaoPagamento',6),$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$12) RETURNING id`,[s.groupId,s.empresaId,d.nome,d.descricao??null,d.codigo_condicao_legado??null,d.origem??'ERP',d.legacy_id??null,d.legacy_code??null,d.source_system??null,d.migration_batch??null,d.imported_at??null,a??null]);const id=String(r.rows[0].id);await q.query('INSERT INTO condicao_pagamento_empresas(group_id,condicao_pagamento_id,empresa_id,created_by,updated_by) VALUES($1,$2,$3,$4,$4)',[s.groupId,id,s.empresaId,a??null]);await this.replaceParcelas({groupId:s.groupId,empresaId:s.empresaId},id,d.parcelas,a,tx);return (await this.row(id,s.groupId,s.empresaId,tx))!;}
  async update(s:CondicaoPagamentoScope,id:string,d:CondicaoPagamentoUpdate,a:string|null|undefined,tx?:DbQueryExecutor){const q=this.q(tx);const c=await this.row(id,s.groupId,s.empresaId,tx);if(!c)return null;await q.query('UPDATE condicoes_pagamento SET nome=$3,descricao=$4,codigo_condicao_legado=$5,updated_by=$6 WHERE id=$1 AND group_id=$2',[id,s.groupId,d.nome??c.nome,d.descricao===undefined?c.descricao:d.descricao,d.codigo_condicao_legado===undefined?c.codigo_condicao_legado:d.codigo_condicao_legado,a??null]);return this.row(id,s.groupId,s.empresaId,tx);}
  async softDelete(s:CondicaoPagamentoScope,id:string,a:string|null|undefined,tx?:DbQueryExecutor){await this.q(tx).query('UPDATE condicoes_pagamento SET ativo=false,updated_by=$3 WHERE id=$1 AND group_id=$2',[id,s.groupId,a??null]);return this.row(id,s.groupId,s.empresaId,tx);} async restore(s:CondicaoPagamentoScope,id:string,a:string|null|undefined,tx?:DbQueryExecutor){await this.q(tx).query('UPDATE condicoes_pagamento SET ativo=true,updated_by=$3 WHERE id=$1 AND group_id=$2',[id,s.groupId,a??null]);return this.row(id,s.groupId,s.empresaId,tx);}
  async linkEmpresa(s:CondicaoPagamentoScope,id:string,e:string,a:string|null|undefined,tx?:DbQueryExecutor){await this.q(tx).query(`INSERT INTO condicao_pagamento_empresas(group_id,condicao_pagamento_id,empresa_id,created_by,updated_by) VALUES($1,$2,$3,$4,$4) ON CONFLICT(condicao_pagamento_id,empresa_id) DO UPDATE SET ativo=true,updated_by=EXCLUDED.updated_by`,[s.groupId,id,e,a??null]);return this.row(id,s.groupId,s.empresaId,tx);} async unlinkEmpresa(s:CondicaoPagamentoScope,id:string,e:string,a:string|null|undefined,tx?:DbQueryExecutor){await this.q(tx).query('UPDATE condicao_pagamento_empresas SET ativo=false,eh_padrao=false,updated_by=$4 WHERE group_id=$1 AND condicao_pagamento_id=$2 AND empresa_id=$3',[s.groupId,id,e,a??null]);return this.row(id,s.groupId,s.empresaId,tx);} restoreEmpresa(s:CondicaoPagamentoScope,id:string,e:string,a:string|null|undefined,tx?:DbQueryExecutor){return this.linkEmpresa(s,id,e,a,tx);}
  async setPadrao(s:{groupId:string;empresaId:string},id:string,a:string|null|undefined,tx?:DbQueryExecutor){const q=this.q(tx);await q.query('UPDATE condicao_pagamento_empresas SET eh_padrao=false,updated_by=$3 WHERE group_id=$1 AND empresa_id=$2',[s.groupId,s.empresaId,a??null]);await q.query('UPDATE condicao_pagamento_empresas SET eh_padrao=true,updated_by=$4 WHERE group_id=$1 AND condicao_pagamento_id=$2 AND empresa_id=$3 AND ativo',[s.groupId,id,s.empresaId,a??null]);return this.row(id,s.groupId,s.empresaId,tx);}
  async replaceParcelas(s:CondicaoPagamentoScope,id:string,p:CondicaoPagamentoParcelaInput[],a:string|null|undefined,tx?:DbQueryExecutor){const q=this.q(tx);await q.query('DELETE FROM condicao_pagamento_parcelas WHERE group_id=$1 AND condicao_pagamento_id=$2',[s.groupId,id]);for(const x of p)await q.query('INSERT INTO condicao_pagamento_parcelas(group_id,condicao_pagamento_id,ordem,dias,percentual,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$6)',[s.groupId,id,x.ordem,x.dias,x.percentual,a??null]);return this.row(id,s.groupId,s.empresaId,tx);}
  async hasActivePadrao(g:string,id:string,tx?:DbQueryExecutor){const r=await this.q(tx).query<any>('SELECT 1 FROM condicao_pagamento_empresas WHERE group_id=$1 AND condicao_pagamento_id=$2 AND ativo AND eh_padrao',[g,id]);return r.rows.length>0;} async countActiveClienteEmpresaRefs(g:string,id:string,tx?:DbQueryExecutor){const r=await this.q(tx).query<any>('SELECT count(*)::int n FROM cliente_empresas WHERE group_id=$1 AND condicao_pagamento_id=$2 AND ativo',[g,id]);return Number(r.rows[0].n);}
}
