export function createMarketplaceSimulationOrders() {
  return [
    {
      origem: 'Mercado Livre',
      id_externo: 'ML-SIM-001',
      numero_pedido_externo: '100001',
      data_pedido_externo: '2026-09-01T12:00:00.000Z',
      cliente_nome: 'Joao Silva Marketplace',
      cliente_cpf_cnpj: '123.456.789-00',
      cliente_email: 'joao@email.com',
      cliente_telefone: '(11) 98765-4321',
      endereco_entrega: {
        cep: '01310-100',
        logradouro: 'Av Paulista',
        numero: '1000',
        bairro: 'Bela Vista',
        cidade: 'Sao Paulo',
        estado: 'SP',
      },
      itens: [{
        descricao: 'Viga V1 - 300cm',
        sku_externo: 'VIGA-300',
        sku_interno: 'VIGA-300',
        quantidade: 10,
        preco_unitario: 150,
        valor_total: 1500,
      }],
      valor_produtos: 1500,
      valor_frete: 50,
      valor_total: 1550,
      comissao_marketplace: 155,
      taxa_marketplace: 23.25,
      status_externo: 'payment_approved',
    },
    {
      origem: 'Shopee',
      id_externo: 'SH-SIM-001',
      numero_pedido_externo: '200001',
      data_pedido_externo: '2026-09-01T13:00:00.000Z',
      cliente_nome: 'Maria Shopee',
      cliente_cpf_cnpj: '987.654.321-00',
      cliente_email: 'maria@email.com',
      cliente_telefone: '(11) 91234-0000',
      endereco_entrega: {
        cep: '01310-200',
        logradouro: 'Rua Augusta',
        numero: '200',
        bairro: 'Consolacao',
        cidade: 'Sao Paulo',
        estado: 'SP',
      },
      itens: [{
        descricao: 'Bloco 20x40',
        sku_externo: 'BLOCO-2040',
        sku_interno: 'BLOCO-2040',
        quantidade: 4,
        preco_unitario: 80,
        valor_total: 320,
      }],
      valor_produtos: 320,
      valor_frete: 20,
      valor_total: 340,
      comissao_marketplace: 34,
      taxa_marketplace: 5.1,
      status_externo: 'payment_approved',
    },
    {
      origem: 'Amazon',
      id_externo: 'AZ-SIM-CANCEL-001',
      numero_pedido_externo: '300001',
      data_pedido_externo: '2026-09-01T14:00:00.000Z',
      cliente_nome: 'Pedro Amazon',
      cliente_cpf_cnpj: '111.222.333-44',
      cliente_email: 'pedro@email.com',
      cliente_telefone: '(11) 90000-1111',
      endereco_entrega: {
        cep: '04001-000',
        logradouro: 'Rua Domingos',
        numero: '50',
        bairro: 'Vila Mariana',
        cidade: 'Sao Paulo',
        estado: 'SP',
      },
      itens: [{
        descricao: 'Chapa 2mm',
        sku_externo: 'CHAPA-2MM',
        sku_interno: 'CHAPA-2MM',
        quantidade: 2,
        preco_unitario: 200,
        valor_total: 400,
      }],
      valor_produtos: 400,
      valor_frete: 30,
      valor_total: 430,
      comissao_marketplace: 43,
      taxa_marketplace: 6.45,
      status_externo: 'cancelled',
    },
  ];
}
