-- ERP-COMERCIAL-360 A1.2A. Aditiva; nao executar na VPS sem gate proprio.
CREATE TABLE IF NOT EXISTS orcamentos (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), group_id UUID NOT NULL REFERENCES groups(id), empresa_id UUID NOT NULL REFERENCES empresas(id), numero VARCHAR(8) NOT NULL, status TEXT NOT NULL DEFAULT 'EM_ABERTO', cliente_empresa_id UUID NOT NULL REFERENCES cliente_empresas(id), condicao_pagamento_id UUID NOT NULL REFERENCES condicoes_pagamento(id), validade_em TIMESTAMPTZ NOT NULL, observacoes TEXT, subtotal NUMERIC(18,6) NOT NULL, desconto NUMERIC(18,6) NOT NULL DEFAULT 0, total NUMERIC(18,6) NOT NULL, ativo BOOLEAN NOT NULL DEFAULT true, created_by UUID REFERENCES profiles(id), updated_by UUID REFERENCES profiles(id), created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc',now()), updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc',now()), UNIQUE(empresa_id,numero), UNIQUE(id,group_id,empresa_id), CHECK(status IN ('EM_ABERTO','CANCELADO')), CHECK(btrim(numero) ~ '^[0-9]{8}$'), CHECK(subtotal>=0 AND desconto>=0 AND total>=0 AND desconto<=subtotal), CHECK((status='CANCELADO') = (ativo=false))
);
CREATE OR REPLACE FUNCTION assert_orcamento_same_tenant() RETURNS TRIGGER AS $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM empresas e WHERE e.id=NEW.empresa_id AND e.group_id=NEW.group_id) THEN RAISE EXCEPTION 'TENANT_FK_MISMATCH: empresa outside group'; END IF;
 IF NOT EXISTS(SELECT 1 FROM cliente_empresas ce WHERE ce.id=NEW.cliente_empresa_id AND ce.group_id=NEW.group_id AND ce.empresa_id=NEW.empresa_id AND ce.ativo) THEN RAISE EXCEPTION 'TENANT_FK_MISMATCH: cliente_empresa outside scope'; END IF;
 IF NOT EXISTS(SELECT 1 FROM condicoes_pagamento c JOIN condicao_pagamento_empresas ce ON ce.condicao_pagamento_id=c.id AND ce.group_id=c.group_id WHERE c.id=NEW.condicao_pagamento_id AND c.group_id=NEW.group_id AND ce.empresa_id=NEW.empresa_id AND c.ativo AND ce.ativo) THEN RAISE EXCEPTION 'TENANT_FK_MISMATCH: condicao_pagamento outside scope'; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql;
CREATE TRIGGER trg_orcamentos_tenant BEFORE INSERT OR UPDATE OF group_id,empresa_id,cliente_empresa_id,condicao_pagamento_id ON orcamentos FOR EACH ROW EXECUTE PROCEDURE assert_orcamento_same_tenant();
CREATE TRIGGER trg_orcamentos_updated_at BEFORE UPDATE ON orcamentos FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE INDEX IF NOT EXISTS idx_orcamentos_scope_page ON orcamentos(group_id,empresa_id,status,numero DESC,id DESC); ALTER TABLE orcamentos ENABLE ROW LEVEL SECURITY; ALTER TABLE orcamentos FORCE ROW LEVEL SECURITY; REVOKE ALL ON TABLE orcamentos FROM PUBLIC;
CREATE TABLE IF NOT EXISTS orcamento_itens (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), group_id UUID NOT NULL REFERENCES groups(id), empresa_id UUID NOT NULL REFERENCES empresas(id), orcamento_id UUID NOT NULL REFERENCES orcamentos(id), produto_id UUID NOT NULL REFERENCES produtos(id), unidade_id UUID NOT NULL REFERENCES unidades_medida(id), descricao_snapshot TEXT NOT NULL, unidade_snapshot TEXT NOT NULL, quantidade NUMERIC(18,6) NOT NULL, preco_unitario NUMERIC(18,6) NOT NULL, desconto NUMERIC(18,6) NOT NULL DEFAULT 0, subtotal NUMERIC(18,6) NOT NULL, total NUMERIC(18,6) NOT NULL, ativo BOOLEAN NOT NULL DEFAULT true, created_by UUID REFERENCES profiles(id), updated_by UUID REFERENCES profiles(id), created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc',now()), updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc',now()), FOREIGN KEY(orcamento_id,group_id,empresa_id) REFERENCES orcamentos(id,group_id,empresa_id), CHECK(btrim(descricao_snapshot)<>'' AND btrim(unidade_snapshot)<>''), CHECK(quantidade>0 AND preco_unitario>=0 AND desconto>=0 AND subtotal>=0 AND total>=0 AND desconto<=subtotal)
);
CREATE OR REPLACE FUNCTION assert_orcamento_item_same_tenant() RETURNS TRIGGER AS $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM orcamentos o WHERE o.id=NEW.orcamento_id AND o.group_id=NEW.group_id AND o.empresa_id=NEW.empresa_id) THEN RAISE EXCEPTION 'TENANT_FK_MISMATCH: item outside orcamento scope'; END IF;
 IF NOT EXISTS(SELECT 1 FROM produtos p WHERE p.id=NEW.produto_id AND p.group_id=NEW.group_id AND p.empresa_id=NEW.empresa_id AND p.unidade_medida_id=NEW.unidade_id) THEN RAISE EXCEPTION 'TENANT_FK_MISMATCH: produto outside scope'; END IF;
 IF NOT EXISTS(SELECT 1 FROM unidades_medida u WHERE u.id=NEW.unidade_id AND u.group_id=NEW.group_id) THEN RAISE EXCEPTION 'TENANT_FK_MISMATCH: unidade outside group'; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql;
CREATE TRIGGER trg_orcamento_itens_tenant BEFORE INSERT OR UPDATE OF group_id,empresa_id,orcamento_id,produto_id,unidade_id ON orcamento_itens FOR EACH ROW EXECUTE PROCEDURE assert_orcamento_item_same_tenant();
CREATE TRIGGER trg_orcamento_itens_updated_at BEFORE UPDATE ON orcamento_itens FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE INDEX IF NOT EXISTS idx_orcamento_itens_scope ON orcamento_itens(group_id,empresa_id,orcamento_id,created_at); ALTER TABLE orcamento_itens ENABLE ROW LEVEL SECURITY; ALTER TABLE orcamento_itens FORCE ROW LEVEL SECURITY; REVOKE ALL ON TABLE orcamento_itens FROM PUBLIC;
COMMENT ON TABLE orcamentos IS 'Comercial 360: agregado de orcamento, tenant-scoped e fail-closed.'; COMMENT ON TABLE orcamento_itens IS 'Snapshots imutaveis de produto/unidade/preco do orcamento.';
-- Rollback somente com backup/gate: DROP TABLE orcamento_itens; DROP TABLE orcamentos; DROP FUNCTION assert_orcamento_item_same_tenant(); DROP FUNCTION assert_orcamento_same_tenant();
