/**
 * Dataset sintético isolado para GO-LIVE-HML-01 (Opção A).
 * IDs com prefixo hml_* — apenas memória de teste; não grava app/localStorage.
 */

export const HML_IDS = Object.freeze({
  groupId: 'hml_grupo_cpa',
  empresaId: 'hml_empresa_cpa',
  empresaForbiddenId: 'hml_empresa_outra',
  customerA: 'hml_cliente_a',
  customerB: 'hml_cliente_b',
  seller: 'hml_vendedor_1',
  priceTable: 'hml_tabela_preco_1',
  paymentTerm: 'hml_condicao_1',
  productActive: 'hml_produto_ativo',
  productInactive: 'hml_produto_inativo',
  productNoPrice: 'hml_produto_sem_preco',
  productNoStock: 'hml_produto_sem_estoque',
  catalog: 'hml_catalogo_1',
  category: 'hml_grupo_produto_1',
  unit: 'hml_unidade_kg',
  workA: 'hml_obra_a',
  workB: 'hml_obra_b',
  project: 'hml_projeto_1',
  costCenter: 'hml_cc_1',
  order: 'hml_pedido_1',
  quote: 'hml_orcamento_1',
  receivable: 'hml_cr_1',
  delivery: 'hml_entrega_1',
  chat: 'hml_chat_1',
  armacao: 'hml_armacao_1',
  opportunity: 'hml_oportunidade_1',
  nfe: 'hml_nfe_1',
  externalUserAdmin: 'hml_user_admin',
  externalUserBuyer: 'hml_user_comprador',
  externalUserFinance: 'hml_user_financeiro',
  externalUserConsulta: 'hml_user_consulta',
});

export const HML_ROLES = Object.freeze(['ADMIN_EMPRESA', 'COMPRADOR', 'FINANCEIRO', 'CONSULTA']);

const stamp = '2026-09-15T12:00:00.000Z';
const scopeFields = () => ({ group_id: HML_IDS.groupId, empresa_id: HML_IDS.empresaId });

const link = ({ externalUserId, customerId, role, allowedWorkIds = [], allWorks = false, status = 'aprovado' }) => ({
  id: `hml_link_${externalUserId}`,
  tipo_solicitacao: 'vinculo_site_cpa_cliente',
  entidade_alvo: 'Cliente',
  entidade_alvo_id: customerId,
  ...scopeFields(),
  status,
  dados_propostos: {
    source: 'SITE_CPA',
    externalUserId,
    erpCustomerId: customerId,
    role,
    ...(allWorks ? { allWorks: true } : { allowedWorkIds }),
  },
});

const customer = ({ id, razao }) => ({
  id,
  ...scopeFields(),
  cnpj: id === HML_IDS.customerA ? '11222333000181' : '99888777000166',
  codigo: id === HML_IDS.customerA ? 'HML-CLI-A' : 'HML-CLI-B',
  razao_social: razao,
  nome_fantasia: razao,
  status: 'Ativo',
  tipo: 'Pessoa Juridica',
  vendedor_responsavel_id: HML_IDS.seller,
  condicao_comercial: {
    tabela_preco_id: HML_IDS.priceTable,
    forma_pagamento_padrao_id: HML_IDS.paymentTerm,
    forma_pagamento_padrao_nome: 'Boleto HML 30',
    limite_credito: 50000,
    limite_credito_utilizado: 0,
  },
  endereco_principal: {
    id: `${id}_end`,
    tipo: 'ENTREGA',
    logradouro: 'Rua HML',
    numero: '100',
    cidade: 'Sao Paulo',
    estado: 'SP',
    cep: '01001000',
  },
  locais_entrega: [
    {
      id: HML_IDS.workA,
      tipo: 'OBRA',
      obra: true,
      nome: 'Obra HML A',
      logradouro: 'Obra A',
      numero: '1',
      cidade: 'Sao Paulo',
      estado: 'SP',
      ativo: true,
    },
    {
      id: HML_IDS.workB,
      tipo: 'OBRA',
      obra: true,
      nome: 'Obra HML B',
      logradouro: 'Obra B',
      numero: '2',
      cidade: 'Campinas',
      estado: 'SP',
      ativo: true,
    },
  ],
  updated_date: stamp,
});

const product = ({ id, descricao, status = 'Ativo', preco_venda = 10, estoque_atual = 100, ...rest }) => ({
  id,
  ...scopeFields(),
  codigo: id.replace('hml_', 'HML-').toUpperCase(),
  descricao,
  grupo_produto_id: HML_IDS.category,
  status,
  unidade_medida_id: HML_IDS.unit,
  unidade_medida: 'KG',
  exibir_no_site: status === 'Ativo',
  preco_venda,
  estoque_atual,
  estoque_reservado: 0,
  quantidade_minima_venda: 1,
  multiplo_venda: 1,
  custo_medio: 5,
  margem_minima_percentual: 10,
  observacoes: 'interno-hml-nao-expor',
  updated_date: stamp,
  ...rest,
});

/**
 * Store in-memory puro para o harness. Clone a cada createSiteCpaHmlDataset().
 */
export const createSiteCpaHmlDataset = (overrides = {}) => {
  const ids = { ...HML_IDS, ...(overrides.ids || {}) };
  const customers = [
    customer({ id: ids.customerA, razao: 'Cliente HML A Ltda' }),
    customer({ id: ids.customerB, razao: 'Cliente HML B Ltda' }),
  ];
  const links = [
    link({
      externalUserId: ids.externalUserAdmin,
      customerId: ids.customerA,
      role: 'ADMIN_EMPRESA',
      allWorks: true,
    }),
    link({
      externalUserId: ids.externalUserBuyer,
      customerId: ids.customerA,
      role: 'COMPRADOR',
      allowedWorkIds: [ids.workA],
    }),
    link({
      externalUserId: ids.externalUserFinance,
      customerId: ids.customerA,
      role: 'FINANCEIRO',
      allWorks: true,
    }),
    link({
      externalUserId: ids.externalUserConsulta,
      customerId: ids.customerA,
      role: 'CONSULTA',
      allowedWorkIds: [ids.workA],
    }),
  ];
  const products = [
    product({ id: ids.productActive, descricao: 'Produto HML ativo' }),
    product({ id: ids.productInactive, descricao: 'Produto HML inativo', status: 'Inativo', exibir_no_site: false }),
    product({ id: ids.productNoPrice, descricao: 'Produto HML sem preco', preco_venda: null }),
    product({ id: ids.productNoStock, descricao: 'Produto HML sem estoque', estoque_atual: 0 }),
  ];

  const records = {
    Empresa: [
      { id: ids.empresaId, group_id: ids.groupId, razao_social: 'CPA HML Ferro e Aco' },
      { id: ids.empresaForbiddenId, group_id: ids.groupId, razao_social: 'Empresa HML nao permitida' },
    ],
    Cliente: customers,
    SolicitacaoAprovacao: links,
    Colaborador: [{
      id: ids.seller,
      ...scopeFields(),
      nome_completo: 'Vendedor HML',
      nome: 'Vendedor HML',
      status: 'Ativo',
      ativo: true,
    }],
    ContatoB2B: [],
    Produto: products,
    CatalogoWeb: [{
      id: ids.catalog,
      ...scopeFields(),
      ativo: true,
      nome: 'Catalogo HML',
    }],
    GrupoProduto: [{
      id: ids.category,
      ...scopeFields(),
      nome: 'Aco HML',
      status: 'Ativo',
    }],
    UnidadeMedida: [{
      id: ids.unit,
      ...scopeFields(),
      codigo: 'KG',
      descricao: 'Quilograma',
    }],
    FormaPagamento: [{
      id: ids.paymentTerm,
      ...scopeFields(),
      nome: 'Boleto HML 30',
      ativo: true,
      status: 'Ativo',
    }],
    TabelaPreco: [{
      id: ids.priceTable,
      ...scopeFields(),
      nome: 'Tabela HML',
      ativo: true,
      itens: [{ produto_id: ids.productActive, preco: 10 }],
    }],
    Pedido: [{
      id: ids.order,
      tipo: 'Pedido',
      origem_pedido: 'SITE_CPA',
      ...scopeFields(),
      cliente_id: ids.customerA,
      site_external_user_id: ids.externalUserBuyer,
      status: 'Aprovado',
      status_pagamento: 'Pendente',
      pagamento_confirmado: false,
      valor_total: 100,
      obra_id: ids.workA,
      itens: [{ produto_id: ids.productActive, quantidade: 10, preco_unitario: 10 }],
      created_date: stamp,
      updated_date: stamp,
    }],
    Oportunidade: [{
      id: ids.opportunity,
      ...scopeFields(),
      cliente_id: ids.customerA,
      titulo: 'Oportunidade HML',
      status: 'Aberta',
      vendedor_id: ids.seller,
      created_date: stamp,
    }],
    NotaFiscal: [{
      id: ids.nfe,
      ...scopeFields(),
      cliente_id: ids.customerA,
      pedido_id: ids.order,
      status: 'Autorizada',
      numero: '1001',
      xml_uri: 'private://hml/nfe/hml_nfe_1.xml',
      danfe_uri: 'private://hml/nfe/hml_nfe_1.pdf',
      created_date: stamp,
    }],
    ContaReceber: [{
      id: ids.receivable,
      ...scopeFields(),
      cliente_id: ids.customerA,
      pedido_id: ids.order,
      valor: 100,
      valor_recebido: 0,
      status: 'Pendente',
      data_vencimento: '2026-10-15',
      detalhes_pagamento: {},
    }],
    Entrega: [{
      id: ids.delivery,
      ...scopeFields(),
      cliente_id: ids.customerA,
      pedido_id: ids.order,
      obra_id: ids.workA,
      status: 'Em Transito',
      created_date: stamp,
    }],
    ConversaOmnicanal: [{
      id: ids.chat,
      ...scopeFields(),
      cliente_id: ids.customerA,
      status: 'aberta',
      canal: 'SITE_CPA',
      obra_id: ids.workA,
      created_date: stamp,
    }],
    MensagemOmnicanal: [{
      id: 'hml_msg_1',
      conversa_id: ids.chat,
      ...scopeFields(),
      cliente_id: ids.customerA,
      tipo: 'texto',
      corpo: 'Mensagem publica HML',
      interno: false,
      created_date: stamp,
    }, {
      id: 'hml_msg_interna',
      conversa_id: ids.chat,
      ...scopeFields(),
      cliente_id: ids.customerA,
      tipo: 'nota',
      corpo: 'Nota interna HML — nao publicar',
      interno: true,
      created_date: stamp,
    }],
    Projeto: [{
      id: ids.project,
      ...scopeFields(),
      cliente_id: ids.customerA,
      obra_id: ids.workA,
      nome: 'Projeto HML Terreo',
      status: 'Ativo',
      ativo: true,
    }, {
      id: ids.armacao,
      ...scopeFields(),
      cliente_id: ids.customerA,
      nome: 'Armacao HML',
      tipo: 'Armação',
      status: 'Rascunho',
      origem: 'SITE_CPA',
      site_armacao_package: true,
      site_external_armacao_id: 'hml_arm_ext_1',
      site_external_user_id: ids.externalUserAdmin,
      site_armacao_version: 1,
      site_armacao_status: 'DRAFT',
      site_customer_confirmed: false,
      site_technical_approved: false,
      site_production_released: false,
      site_op_created: false,
      obra_id: ids.workA,
      created_date: stamp,
    }],
    CentroCusto: [{
      id: ids.costCenter,
      ...scopeFields(),
      cliente_id: ids.customerA,
      obra_id: ids.workA,
      projeto_id: ids.project,
      nome: 'CC HML',
      status: 'Ativo',
      ativo: true,
    }],
    TabelaPrecoItem: [{
      id: 'hml_tpi_1',
      ...scopeFields(),
      tabela_preco_id: ids.priceTable,
      produto_id: ids.productActive,
      preco: 10,
      ativo: true,
      updated_date: stamp,
    }],
    ConfiguracaoGatewayPagamento: [],
    GatewayPagamento: [],
    IntegracaoEvento: [],
    OrdemProducao: [],
    AuditLog: [],
  };

  return {
    ids,
    roles: HML_ROLES,
    stamp,
    scope: { groupId: ids.groupId, empresaId: ids.empresaId, scopeType: 'empresa' },
    records,
    /** Snapshot serializável (sem funções) para auditoria de fixture. */
    inventory: {
      customers: [ids.customerA, ids.customerB],
      roles: [...HML_ROLES],
      products: {
        active: ids.productActive,
        inactive: ids.productInactive,
        noPrice: ids.productNoPrice,
        noStock: ids.productNoStock,
      },
      works: [ids.workA, ids.workB],
      project: ids.project,
      costCenter: ids.costCenter,
      order: ids.order,
      quoteSeed: ids.quote,
      receivable: ids.receivable,
      delivery: ids.delivery,
      chat: ids.chat,
      armacao: ids.armacao,
      opportunity: ids.opportunity,
      nfe: ids.nfe,
      documentPolicy: 'ownership_and_path_traversal_only',
      externalDownload: 'BLOCKED_without_private_storage',
    },
  };
};
