import assert from 'node:assert/strict'; import test from 'node:test'; import type { DbQueryExecutor } from '../src/db/client.js'; import { AppError } from '../src/api/errors.js'; import { InMemoryOrcamentoRepository } from '../src/repositories/inMemoryOrcamentoRepository.js'; import { OrcamentoService } from '../src/services/orcamentoService.js';
const groupId='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',empresaId='cccccccc-cccc-4ccc-8ccc-cccccccccccc',otherEmpresa='dddddddd-dddd-4ddd-8ddd-dddddddddddd'; const clienteId='11111111-1111-4111-8111-111111111111',condicaoId='22222222-2222-4222-8222-222222222222',produtoId='33333333-3333-4333-8333-333333333333',unidadeId='44444444-4444-4444-8444-444444444444'; const ctx={requestId:'req-a21a',actorId:'55555555-5555-4555-8555-555555555555',groupId,empresaId}; const payload={cliente_empresa_id:clienteId,condicao_pagamento_id:condicaoId,validade_em:'2027-01-01T00:00:00.000Z',itens:[{produto_id:produtoId,unidade_id:unidadeId,descricao:'Produto sintetico',unidade_sigla:'UN',quantidade:'2',preco_unitario:'10',desconto:'1'}]};
class TrackingRepo extends InMemoryOrcamentoRepository { transactions=0; received?:DbQueryExecutor; private executor:DbQueryExecutor={query:async()=>({rows:[],command:'',rowCount:0,oid:0,fields:[]})}; async withTransaction<T>(fn:(executor?:DbQueryExecutor)=>Promise<T>){this.transactions+=1;return super.withTransaction(()=>fn(this.executor));} async create(scope:Parameters<InMemoryOrcamentoRepository['create']>[0],data:Parameters<InMemoryOrcamentoRepository['create']>[1],executor?:DbQueryExecutor){this.received=executor;return super.create(scope,data,executor);}}
function fixture(overrides:{tenantFails?:boolean;cliente?:unknown;produto?:unknown;unidade?:unknown;condicao?:unknown}={}){const repo=new TrackingRepo();const service=new OrcamentoService(repo,{assertEmpresaInGroup:async()=>{if(overrides.tenantFails)throw new AppError(409,'TENANT_MISMATCH','tenant mismatch');}},{getEmpresaLinkById:async()=>overrides.cliente===undefined?{id:clienteId,ativo:true,bloqueado:false,habilitado_operacao:true}:overrides.cliente} as any,{getById:async()=>overrides.produto===undefined?{id:produtoId,ativo:true,unidade_medida_id:unidadeId}:overrides.produto} as any,{getById:async()=>overrides.unidade===undefined?{id:unidadeId,ativo:true}:overrides.unidade} as any,{get:async()=>overrides.condicao===undefined?{id:condicaoId,ativo:true}:overrides.condicao} as any);return{repo,service};} async function code(p:Promise<unknown>){try{await p;return'NONE';}catch(error){return(error as AppError).code;}}
test('create valida referencias calcula total e usa uma transacao',async()=>{const{repo,service}=fixture(),row=await service.create(ctx,payload);assert.equal(row.total,'19.000000');assert.equal(repo.transactions,1);assert.ok(repo.received);});
test('create rejeita campos extras totais status e tenant',async()=>{const{service}=fixture();for(const field of ['total','status','groupId','empresaId'])assert.equal(await code(service.create(ctx,{...payload,[field]:'indevido'})),'VALIDATION_ERROR');});
test('exige group empresa actor e empresa vinculada',async()=>{const{service}=fixture();assert.equal(await code(service.list({...ctx,groupId:''})),'GROUP_ID_REQUIRED');assert.equal(await code(service.list({...ctx,empresaId:null})),'EMPRESA_ID_REQUIRED');assert.equal(await code(service.list({...ctx,actorId:null})),'ACTOR_REQUIRED');assert.equal(await code(fixture({tenantFails:true}).service.list(ctx)),'TENANT_MISMATCH');});
test('bloqueia ClienteEmpresa e Condicao fora do tenant',async()=>{assert.equal(await code(fixture({cliente:null}).service.create(ctx,payload)),'ORCAMENTO_CLIENTE_INVALIDO');assert.equal(await code(fixture({condicao:null}).service.create(ctx,payload)),'ORCAMENTO_CONDICAO_INVALIDA');});
test('bloqueia Produto cross-tenant e Unidade incompatível',async()=>{assert.equal(await code(fixture({produto:null}).service.create(ctx,payload)),'ORCAMENTO_PRODUTO_INVALIDO');assert.equal(await code(fixture({produto:{id:produtoId,ativo:true,unidade_medida_id:'66666666-6666-4666-8666-666666666666'}}).service.create(ctx,payload)),'ORCAMENTO_UNIDADE_INVALIDA');assert.equal(await code(fixture({unidade:null}).service.create(ctx,payload)),'ORCAMENTO_UNIDADE_INVALIDA');});
test('get valida id e nao revela cross-tenant',async()=>{const{service}=fixture(),created=await service.create(ctx,payload);assert.equal((await service.get(ctx,created.id)).id,created.id);assert.equal(await code(service.get(ctx,'invalido')),'VALIDATION_ERROR');assert.equal(await code(service.get({...ctx,empresaId:otherEmpresa},created.id)),'ORCAMENTO_NOT_FOUND');});
test('list normaliza pagina e preserva tenant',async()=>{const{service}=fixture();await service.create(ctx,payload);const page=await service.list(ctx,{limit:999,offset:-2});assert.deepEqual(page.meta,{limit:200,offset:0,total:1,hasMore:false});assert.equal(page.data.length,1);assert.equal((await service.list({...ctx,empresaId:otherEmpresa})).data.length,0);});